import React, { createContext, useContext, useState, ReactNode } from 'react';

// 支持的语言类型
export type Language = 'en' | 'zh-CN' | 'zh-TW' | 'ja';

// 翻译键值类型
type TranslationsType = {
  [key in Language]: {
    [key: string]: string;
  };
};

// 语言上下文类型
interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// 翻译内容
const translations: TranslationsType = {
  'en': {
    'app.title': 'NameBridge',
    'app.subtitle': 'Foreign to Chinese Name Generator',
    'app.description': 'Enter any foreign name and receive 6 magical Chinese name suggestions with meanings',
    'app.start': 'Start Your Chinese Name Journey',
    'app.startDescription': 'Enter your name and we\'ll generate 6 magical Chinese name suggestions with meanings',
    'app.try': 'Try',
    'app.generate': 'Generate Chinese Names',
    'app.loading': 'Magic in progress...',
    'app.copy': 'Copy',
    'app.copied': 'Copied!',
    'app.namesFor': 'Chinese Names for',
    'app.chooseYourFavorite': 'Choose your favorite Chinese name and click to copy',
    'app.notFound': 'Mysterious Name Not Found',
    'app.notFoundDesc': 'No Chinese name suggestions found for',
    'app.tryAgain': 'Please try again or enter a different name',
    'app.waitMessage': 'Please wait, DeepSeek AI is working...',
    'app.enterName': 'Enter any name, like: Michael, Sarah, David, 王小明...',
    'app.nameRequired': 'Please enter a name before generating',
    'app.apiError': 'API error occurred. Please try again later.',
    'app.generateError': 'Error generating names. Trying local database...',
    'app.faq.title': 'Frequently Asked Questions',
    'app.faq.subtitle': 'Find answers to common questions about our service',
    'app.faq.contactButton': 'Still have questions? Contact us',
    'app.faq.contactTitle': 'Still have questions?',
    'app.faq.contactDesc': 'Feel free to reach out, we\'ll get back to you as soon as possible.',
    'app.faq.q5': 'How do I contact customer support?',
    'app.faq.a5': 'You can reach our customer support team by sending an email to y206186.gmail.com. We typically respond within 24-48 hours.',
    'app.about.title': 'About NameBridge',
    'app.about.description': 'NameBridge is a tool designed to help bridge cultural gaps through names. Our platform uses advanced AI to generate culturally appropriate Chinese names for English names and vice versa.',
    'app.about.mission': 'Our mission is to promote cultural understanding and help people connect across languages and cultures through the power of meaningful names.',
    'app.pricing.title': 'Choose Your Plan',
    'app.pricing.subtitle': 'Select the plan that works best for you',
    'app.pricing.monthly.title': 'Monthly Plan',
    'app.pricing.monthly.duration': 'month',
    'app.pricing.quarterly.title': 'Quarterly Plan',
    'app.pricing.quarterly.duration': '3 months',
    'app.pricing.annual.title': 'Annual Plan',
    'app.pricing.annual.duration': 'year',
    'app.pricing.features.unlimited': 'Unlimited name generations',
    'app.pricing.features.meaningExplanation': 'Detailed name meaning explanations',
    'app.pricing.features.basicSupport': 'Basic customer support',
    'app.pricing.features.priority': 'Priority generation requests',
    'app.pricing.features.standardSupport': 'Standard customer support',
    'app.pricing.features.premiumSupport': 'Premium customer support',
    'app.pricing.features.customNames': 'Custom name design',
    'app.pricing.features.saving': 'Save about 33% versus monthly',
    'app.pricing.features.bigSaving': 'Save about 42% versus monthly',
    'app.pricing.subscribe': 'Subscribe Now',
    'app.pricing.bestValue': 'Best Value',
    'app.pricing.comingSoon': 'Payment system coming soon! Currently, you can try all features for free.',
    'app.pricing.questions': 'If you have any questions, please contact:',
    'nav.home': 'Home',
    'nav.search': 'Generator',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.about': 'About',
    'app.faq.q1': 'How does the Chinese name generation work?',
    'app.faq.a1': 'We use advanced AI technology to analyze your name and create meaningful Chinese equivalents, considering pronunciation, meaning and cultural context.',
    'app.faq.q2': 'Are the generated names culturally appropriate?',
    'app.faq.a2': 'Yes, our system creates names that sound natural to native Chinese speakers while preserving elements of your original name.',
    'app.faq.q3': 'What do the different name types mean?',
    'app.faq.a3': 'Transliteration focuses on similar sounds, meaning translation captures the spirit of your name, and creative names offer artistic interpretations.',
    'app.faq.q4': 'Can I use this name officially?',
    'app.faq.a4': 'While these names are culturally appropriate, official documents may require standard transliteration methods. These suggestions are primarily for personal use.',
    'app.footer.copyright': 'Find the perfect Chinese expression for any name',
    'app.footer.feature1': 'Transliteration, Meaning & Creative Names',
    'app.footer.feature2': 'Professional Chinese Name Suggestions',
    'app.footer.feature3': 'One-Click Copy',
    'app.language': 'Language',
  },
  'zh-CN': {
    'app.title': '名字桥',
    'app.subtitle': '外国名转中文名生成器',
    'app.description': '输入任意外国名字，获得6个带有寓意的魔法中文名建议',
    'app.start': '开始您的中文名之旅',
    'app.startDescription': '输入您的名字，我们将为您生成6个带有寓意的中文名建议',
    'app.try': '尝试',
    'app.generate': '生成中文名',
    'app.loading': '魔法生成中...',
    'app.copy': '复制',
    'app.copied': '已复制！',
    'app.namesFor': '为以下名字生成的中文名：',
    'app.chooseYourFavorite': '选择您最喜欢的中文名，点击即可复制',
    'app.notFound': '未找到匹配的名字',
    'app.notFoundDesc': '未能为以下名字找到建议：',
    'app.tryAgain': '请重试或输入其他名字',
    'app.waitMessage': '请稍等，DeepSeek AI正在工作...',
    'app.enterName': '输入任意名字，如：Michael, Sarah, David, 王小明...',
    'app.nameRequired': '请在生成前输入名字',
    'app.apiError': 'API发生错误，请稍后再试。',
    'app.generateError': '生成名字时出错，尝试使用本地数据库...',
    'app.faq.title': '常见问题',
    'app.faq.subtitle': '查找关于我们服务的常见问题解答',
    'app.faq.contactButton': '还有问题？联系我们',
    'app.faq.contactTitle': '还有其他问题？',
    'app.faq.contactDesc': '随时联系我们，我们会尽快回复您。',
    'app.faq.q5': '如何联系客服？',
    'app.faq.a5': '您可以发送电子邮件至 y206186.gmail.com 与我们的客服团队联系。我们通常会在24-48小时内回复。',
    'app.about.title': '关于名字桥',
    'app.about.description': '名字桥是一个旨在通过名字帮助跨越文化鸿沟的工具。我们的平台使用先进的人工智能为英文名生成文化上合适的中文名，反之亦然。',
    'app.about.mission': '我们的使命是通过有意义的名字的力量促进文化理解，帮助人们跨越语言和文化进行联系。',
    'app.pricing.title': '选择您的计划',
    'app.pricing.subtitle': '选择最适合您的计划，享受专业的中文名生成服务',
    'app.pricing.monthly.title': '月度计划',
    'app.pricing.monthly.duration': '月',
    'app.pricing.quarterly.title': '季度计划',
    'app.pricing.quarterly.duration': '3个月',
    'app.pricing.annual.title': '年度计划',
    'app.pricing.annual.duration': '年',
    'app.pricing.features.unlimited': '无限生成中文名',
    'app.pricing.features.meaningExplanation': '详细名字含义解释',
    'app.pricing.features.basicSupport': '基本客户支持',
    'app.pricing.features.priority': '优先生成请求',
    'app.pricing.features.standardSupport': '标准客户支持',
    'app.pricing.features.premiumSupport': '高级客户支持',
    'app.pricing.features.customNames': '个性化名字定制',
    'app.pricing.features.saving': '比月付节省约33%',
    'app.pricing.features.bigSaving': '比月付节省约42%',
    'app.pricing.subscribe': '立即订阅',
    'app.pricing.bestValue': '最超值',
    'app.pricing.comingSoon': '支付系统即将上线！目前您可以免费试用所有功能。',
    'app.pricing.questions': '如有任何问题，请联系：',
    'nav.home': '首页',
    'nav.search': '生成器',
    'nav.pricing': '价格',
    'nav.faq': '常见问题',
    'nav.about': '关于我们',
    'app.faq.q1': '中文名字生成是如何工作的？',
    'app.faq.a1': '我们使用先进的人工智能技术分析您的名字，并创建有意义的中文对应名，同时考虑发音、含义和文化背景。',
    'app.faq.q2': '生成的名字在文化上合适吗？',
    'app.faq.a2': '是的，我们的系统创建的名字对于中文母语使用者来说听起来自然，同时保留了您原始名字的元素。',
    'app.faq.q3': '不同的名字类型有什么含义？',
    'app.faq.a3': '音译侧重于相似的发音，意译侧重于名字的内涵，创意名则提供了更具艺术性的诠释。',
    'app.faq.q4': '我可以正式使用这个名字吗？',
    'app.faq.a4': '虽然这些名字在文化上是合适的，但官方文件可能需要使用标准的音译方法。这些建议主要供个人使用。',
    'app.footer.copyright': '为任何名字找到完美的中文表达',
    'app.footer.feature1': '支持音译、意译和创意型名字',
    'app.footer.feature2': '专业的中文名建议',
    'app.footer.feature3': '一键复制使用',
    'app.language': '语言',
  },
  'zh-TW': {
    'app.title': '名字橋',
    'app.subtitle': '外國名轉中文名生成器',
    'app.description': '輸入任意外國名字，獲得6個帶有寓意的魔法中文名建議',
    'app.start': '開始您的中文名之旅',
    'app.startDescription': '輸入您的名字，我們將為您生成6個帶有寓意的中文名建議',
    'app.try': '嘗試',
    'app.generate': '生成中文名',
    'app.loading': '魔法生成中...',
    'app.copy': '複製',
    'app.copied': '已複製！',
    'app.namesFor': '為以下名字生成的中文名：',
    'app.chooseYourFavorite': '選擇您最喜歡的中文名，點擊即可複製',
    'app.notFound': '未找到匹配的名字',
    'app.notFoundDesc': '未能為以下名字找到建議：',
    'app.tryAgain': '請重試或輸入其他名字',
    'app.waitMessage': '請稍等，DeepSeek AI正在工作...',
    'app.enterName': '輸入任意名字，如：Michael, Sarah, David, 王小明...',
    'app.nameRequired': '請在生成前輸入名字',
    'app.apiError': 'API發生錯誤，請稍後再試。',
    'app.generateError': '生成名字時出錯，嘗試使用本地數據庫...',
    'app.faq.title': '常見問題',
    'app.faq.subtitle': '查找關於我們服務的常見問題解答',
    'app.faq.contactButton': '還有問題？聯繫我們',
    'app.faq.contactTitle': '還有其他問題？',
    'app.faq.contactDesc': '隨時聯繫我們，我們會儘快回复您。',
    'app.faq.q5': '如何聯繫客服？',
    'app.faq.a5': '您可以發送電子郵件至 y206186.gmail.com 與我們的客服團隊聯繫。我們通常會在24-48小時內回复。',
    'app.about.title': '關於名字橋',
    'app.about.description': '名字橋是一個旨在通過名字幫助跨越文化鴻溝的工具。我們的平台使用先進的人工智能為英文名生成文化上合適的中文名，反之亦然。',
    'app.about.mission': '我們的使命是通過有意義的名字的力量促進文化理解，幫助人們跨越語言和文化進行聯繫。',
    'app.pricing.title': '選擇您的計劃',
    'app.pricing.subtitle': '選擇最適合您的計劃，享受專業的中文名生成服務',
    'app.pricing.monthly.title': '月度計劃',
    'app.pricing.monthly.duration': '月',
    'app.pricing.quarterly.title': '季度計劃',
    'app.pricing.quarterly.duration': '3個月',
    'app.pricing.annual.title': '年度計劃',
    'app.pricing.annual.duration': '年',
    'app.pricing.features.unlimited': '無限生成中文名',
    'app.pricing.features.meaningExplanation': '詳細名字含義解釋',
    'app.pricing.features.basicSupport': '基本客戶支持',
    'app.pricing.features.priority': '優先生成請求',
    'app.pricing.features.standardSupport': '標準客戶支持',
    'app.pricing.features.premiumSupport': '高級客戶支持',
    'app.pricing.features.customNames': '個性化名字定制',
    'app.pricing.features.saving': '比月付節省約33%',
    'app.pricing.features.bigSaving': '比月付節省約42%',
    'app.pricing.subscribe': '立即訂閱',
    'app.pricing.bestValue': '最超值',
    'app.pricing.comingSoon': '支付系統即將上線！目前您可以免費試用所有功能。',
    'app.pricing.questions': '如有任何問題，請聯繫：',
    'nav.home': '首頁',
    'nav.search': '生成器',
    'nav.pricing': '價格',
    'nav.faq': '常見問題',
    'nav.about': '關於我們',
    'app.faq.q1': '中文名字生成是如何工作的？',
    'app.faq.a1': '我們使用先進的人工智能技術分析您的名字，並創建有意義的中文對應名，同時考慮發音、含義和文化背景。',
    'app.faq.q2': '生成的名字在文化上合適嗎？',
    'app.faq.a2': '是的，我們的系統創建的名字對於中文母語使用者來說聽起來自然，同時保留了您原始名字的元素。',
    'app.faq.q3': '不同的名字類型有什麼含義？',
    'app.faq.a3': '音譯側重於相似的發音，意譯側重於名字的內涵，創意名則提供了更具藝術性的詮釋。',
    'app.faq.q4': '我可以正式使用這個名字嗎？',
    'app.faq.a4': '雖然這些名字在文化上是合適的，但官方文件可能需要使用標準的音譯方法。這些建議主要供個人使用。',
    'app.footer.copyright': '為任何名字找到完美的中文表達',
    'app.footer.feature1': '支持音譯、意譯和創意型名字',
    'app.footer.feature2': '專業的中文名建議',
    'app.footer.feature3': '一鍵複製使用',
    'app.language': '語言',
  },
  'ja': {
    'app.title': 'ネームブリッジ',
    'app.subtitle': '外国名から中国語名生成ツール',
    'app.description': '任意の外国名を入力すると、6つの意味のある中国語名の提案が得られます',
    'app.start': '中国語名の旅を始めましょう',
    'app.startDescription': 'お名前を入力すると、6つの意味のある中国語名の提案を生成します',
    'app.try': '試す',
    'app.generate': '中国語名を生成',
    'app.loading': '生成中...',
    'app.copy': 'コピー',
    'app.copied': 'コピーしました！',
    'app.namesFor': '次の名前の中国語名：',
    'app.chooseYourFavorite': 'お気に入りの中国語名を選んでクリックしてコピー',
    'app.notFound': '一致する名前が見つかりません',
    'app.notFoundDesc': '次の名前の提案が見つかりませんでした：',
    'app.tryAgain': 'もう一度試すか、別の名前を入力してください',
    'app.waitMessage': 'お待ちください、DeepSeek AIが処理中です...',
    'app.enterName': '任意の名前を入力：Michael, Sarah, David, 田中...',
    'app.nameRequired': '生成する前に名前を入力してください',
    'app.apiError': 'APIエラーが発生しました。後でもう一度お試しください。',
    'app.generateError': '名前の生成中にエラーが発生しました。ローカルデータベースを使用しています...',
    'app.faq.title': 'よくある質問',
    'app.faq.subtitle': '当サービスに関する一般的な質問への回答を見つける',
    'app.faq.contactButton': '質問がまだありますか？お問い合わせください',
    'app.faq.contactTitle': '他に質問がありますか？',
    'app.faq.contactDesc': 'お気軽にお問い合わせください。できるだけ早くご回答いたします。',
    'app.faq.q1': '中国語名の生成はどのように機能しますか？',
    'app.faq.a1': '高度なAI技術を使用してお名前を分析し、発音、意味、文化的背景を考慮した有意義な中国語名を作成します。',
    'app.faq.q2': '生成された名前は文化的に適切ですか？',
    'app.faq.a2': 'はい、当システムが作成する名前は中国語ネイティブスピーカーに自然に聞こえるよう設計されており、元のお名前の要素も保持しています。',
    'app.faq.q3': '異なる名前タイプは何を意味しますか？',
    'app.faq.a3': '音訳は類似した発音に焦点を当て、意訳はお名前の精神を捉え、創造的な名前は芸術的な解釈を提供します。',
    'app.faq.q4': 'この名前を正式に使用できますか？',
    'app.faq.a4': 'これらの名前は文化的に適切ですが、公式文書では標準的な音訳方法が必要な場合があります。これらの提案は主に個人使用のためのものです。',
    'app.faq.q5': 'カスタマーサポートにはどうやって連絡すればいいですか？',
    'app.faq.a5': 'y206186.gmail.com 宛にメールを送信することで、カスタマーサポートチームに連絡できます。通常24〜48時間以内に返信いたします。',
    'app.about.title': 'ネームブリッジについて',
    'app.about.description': 'ネームブリッジは、名前を通じて文化的な隔たりを埋めるのを支援するツールです。私たちのプラットフォームは、先進的なAIを使用して、英語名に文化的に適切な中国語名を生成し、その逆も行います。',
    'app.about.mission': '私たちの使命は、意味のある名前の力を通じて文化理解を促進し、人々が言語や文化を超えてつながるのを支援することです。',
    'app.pricing.title': 'プランを選択',
    'app.pricing.subtitle': '最適なプランを選んで、プロフェッショナルな中国語名生成サービスをお楽しみください',
    'app.pricing.monthly.title': '月間プラン',
    'app.pricing.monthly.duration': '月',
    'app.pricing.quarterly.title': '四半期プラン',
    'app.pricing.quarterly.duration': '3ヶ月',
    'app.pricing.annual.title': '年間プラン',
    'app.pricing.annual.duration': '年',
    'app.pricing.features.unlimited': '無制限の名前生成',
    'app.pricing.features.meaningExplanation': '詳細な名前の意味の説明',
    'app.pricing.features.basicSupport': '基本的なカスタマーサポート',
    'app.pricing.features.priority': '優先生成リクエスト',
    'app.pricing.features.standardSupport': '標準カスタマーサポート',
    'app.pricing.features.premiumSupport': 'プレミアムカスタマーサポート',
    'app.pricing.features.customNames': 'カスタム名前デザイン',
    'app.pricing.features.saving': '月額プランより約33%お得',
    'app.pricing.features.bigSaving': '月額プランより約42%お得',
    'app.pricing.subscribe': '今すぐ購読',
    'app.pricing.bestValue': '最高の価値',
    'app.pricing.comingSoon': '決済システム近日公開！現在、すべての機能を無料でお試しいただけます。',
    'app.pricing.questions': 'ご質問がある場合は、こちらまでお問い合わせください：',
    'app.footer.copyright': 'どんな名前にも完璧な中国語表現を',
    'app.footer.feature1': '音訳、意訳、創造的な名前をサポート',
    'app.footer.feature2': 'プロフェッショナルな中国語名の提案',
    'app.footer.feature3': 'ワンクリックでコピー',
    'app.language': '言語',
    'nav.home': 'ホーム',
    'nav.search': 'ジェネレーター',
    'nav.pricing': '料金',
    'nav.faq': 'FAQ',
    'nav.about': '概要',
  }
};

// 创建语言上下文
const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key
});

// 导出语言钩子
export const useLanguage = () => useContext(LanguageContext);

// 语言提供者组件属性
interface LanguageProviderProps {
  children: ReactNode;
}

// 语言提供者组件
export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}; 